version: '3'
services:
  mongodb:
    build: 
      dockerfile: Dockerfile
      context: ./data-persistence/mongodb
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./microservices/user-service
    ports:
      - '6008:6008'
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - /Users/nathan3/Desktop/PracticeEnv/node-microservices-suite/microservices/user-service:/app