
version: '3.8'
services:

  cart: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/cart 
    ports: 
      - "9010:9010" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/cart:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  user: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/user 
    ports: 
      - "9011:9011" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/user:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  customer: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/customer 
    ports: 
      - "9012:9012" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/customer:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  email: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/email 
    ports: 
      - "9013:9013" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/email:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/notification 
    ports: 
      - "9014:9014" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/notification:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/payment 
    ports: 
      - "9015:9015" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/payment:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  product: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/product 
    ports: 
      - "9016:9016" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/product:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  rbac: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/rbac 
    ports: 
      - "9017:9017" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/rbac:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  supplier: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/supplier 
    ports: 
      - "9018:9018" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/supplier:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  upload: 
    build: 
      dockerfile: Dockerfile.dev 
      context: ../../../microservices/upload 
    ports: 
      - "9019:9019" 
    volumes: 
      - /app/node_modules 
      - ../../../microservices/upload:/app 
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    depends_on:
      - cart
      - user
      - customer
      - email
      - notification
      - payment
      - product
      - rbac
      - supplier
      - upload
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4000:80'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      retries: 5
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  krakend:
    image: devopsfaith/krakend:2.7-watch
    ports:
      - '8080:8080'
      - '8090:8090'
    volumes:
      - ./krakend/:/etc/krakend/
    command: ['run','-d','-c','/etc/krakend/krakend.json']