version: '3.8'
services:
  mongodb:
    build: 
      dockerfile: DockerFile
      context: ../../../data-persistence/mongodb
  user-service:
    build:
      dockerfile: DockerFile.dev
      context: ../../../microservices/user-service
    ports:
      - '9003:9003'
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ../../../microservices/user-service:/app
  upload-service:
    build:
      dockerfile: DockerFile.dev
      context: ../../../microservices/upload-service
    ports:
      - '9004:9004'
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ../../../microservices/upload-service:/app
  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      retries: 5
    restart: unless-stopped
  # shared:
  #   build: 
  #     context: ./shared
  #     dockerfile: DockerFile.dev
  #   healthcheck:
  #     test: ["CMD-SHELL", "sleep 1"]
  nginx:
    depends_on:
      - customer-service
      - product-service
      - supplier-service
    restart: always
    build:
      context: ./nginx
      dockerfile: DockerFile.dev
    ports:
      - '4000:80'
  customer-service:
    depends_on:
      rabbitmq:
        condition: service_healthy
      # shared:
      #   condition: service_healthy
    container_name: customer
    restart: always
    build:
      context: ../../../microservices/customer-service
      dockerfile: DockerFile.dev
    ports:
      - 9000:9000
    volumes:
      - /app/node_modules
      - ../../../microservices/customer-service:/app
  supplier-service:
    depends_on:
      rabbitmq:
        condition: service_healthy
      # shared:
      #   condition: service_healthy
    container_name: supplier
    restart: always
    build:
      context: ../../../microservices/supplier-service
      dockerfile: DockerFile.dev
    ports:
      - 9001:9001
    volumes:
      - /app/node_modules
      - ../../../microservices/supplier-service:/app  
  product-service:
    depends_on:
      - rabbitmq
    container_name: product
    restart: always
    build:
      context: ../../../microservices/product-service
      dockerfile: DockerFile.dev
    ports:
      - 9002:9002

    volumes:
      - /app/node_modules
      - ../../../microservices/product-service:/app
  keycloak:
    container_name: keycloak
    depends_on:
        - nginx
    build:
      context: ../../../microservices/rbac-service
      dockerfile: DockerFile.dev
    ports:
      - "9005:9005"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
